server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/atl_omnio_project
    username: postgres
    password: 2000
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    properties:
      hibernate:
        format-sql: true
    open-in-view: false

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

application-description: Omnio application
application-version: 1.0
#feign:
#  client:
#    config:
#      default:
#        connectTimeout: 5000
#        readTimout: 5000
#        loggerLevel: basic
#  httpclient:
#    enable: false
